name: Actualizaci칩n autom치tica

on:
  push:
    branches:
      - main   # o master si usas esa rama

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar el repositorio
        uses: actions/checkout@v4

      - name: Repo actualizado
        run: echo "Se detect칩 un cambio y el workflow se ejecut칩"
